CREATE TABLE PUBLIC.T_ROLES (
  ID      INTEGER     NOT NULL PRIMARY KEY,
  USER_ID INTEGER     NOT NULL,
  ROLE    VARCHAR(45) NOT NULL
);

CREATE TABLE PUBLIC.T_USERS (
  ID       INTEGER           NOT NULL PRIMARY KEY,
  NAME     VARCHAR(45)       NOT NULL,
  PASSWORD VARCHAR(45)       NOT NULL,
  ENABLED  TINYINT DEFAULT 1 NOT NULL
);

CREATE TABLE PUBLIC.T_DVD
(
  ID          INT PRIMARY KEY NOT NULL,
  NAME        VARCHAR(255)    NOT NULL,
  DESCRIPTION VARCHAR(1000)   NOT NULL,
  POSTER      CLOB            NOT NULL,
  POSTER_NAME VARCHAR(255)    NOT NULL,
  OWNER       INT             NOT NULL
);

CREATE TABLE PUBLIC.T_TAKEN_ITEM
(
  ID INT PRIMARY KEY NOT NULL,
  DVD_ID  INT NOT NULL,
  USER_ID INT NOT NULL
);


ALTER TABLE T_DVD
ADD FOREIGN KEY (OWNER) REFERENCES T_USERS (id);

ALTER TABLE T_TAKEN_ITEM
ADD FOREIGN KEY (DVD_ID) REFERENCES T_DVD (id);

ALTER TABLE T_TAKEN_ITEM
ADD FOREIGN KEY (USER_ID) REFERENCES T_USERS (id);

INSERT INTO T_USERS (ID, NAME, PASSWORD, ENABLED) VALUES
  (0, 'Anton', '123', 1);
INSERT INTO T_USERS (ID, NAME, PASSWORD, ENABLED) VALUES
  (1, 'Valera', '123', 1);
INSERT INTO T_USERS (ID, NAME, PASSWORD, ENABLED) VALUES
  (2, 'Sergey', '123', 1);
INSERT INTO T_USERS (ID, NAME, PASSWORD, ENABLED) VALUES
  (3, 'Nick', '123', 1);
